momentohq/client-sdk-rust

- .github/workflows/cd.yml
- README.md
- set_cargo_version.sh
- src/simple_cache_client.rs
- src/utils.rs
- tests/integration_test.rs
- update_cargo_toml.py
This enforces users to pass `NonZeroU64::new(u64).unwrap()` to set default TTL or overwrite default TTL.
If users pass 0 to initialize `NonZeroU64` then `None` will be returned and thrown an error.
This adds an extra layer to make sure users pass an integer other than 0 before they blindly pass 0 without any thoughts.
Also added publish workflow to publish our SDK to crates.io as we merge prs to `main`.
Closes #23
> chore: Update TTL data type to `NonZeroU64` and add publish workflow

- src/simple_cache_client.rs
Allow the `SimpleCacheClientBuilder` default ttl to be modified by
adding a new function. This is necessary if we want to be able to
create several clients with different ttls after initializing the
builder.
For example, this is desirable in the proxy where we want to allow
a different ttl for each cache but use the same underlying grpc
channels.
> feat: allow changing builder default ttl

- Cargo.toml
- src/jwt.rs
Resolves the cargo audit errors by upgrading jsonwebtoken to 8.0.1
and making necessary code changes.
Fixes #40
> fix: resolve cargo audit errors from jsonwebtoken

- src/endpoint_resolver.rs
- src/jwt.rs
- src/response/error.rs
- src/simple_cache_client.rs
- src/utils.rs
Is users paste an invalid auth token, the following error message will be displayed: `Please make sure entered auth token matches your auth token`
Closes #45
> chore: Add more descriptive error message for auth token parse

- src/response/list_signing_keys_response.rs
Adds `Serialize` and `Deserialize` so that consumers can easily pretty-print results of a `ListSigningKeysResponse`
> chore: add Deserialize and Serialize to SigningKey for serde_json support

- Cargo.toml
- src/endpoint_resolver.rs
- src/simple_cache_client.rs
- src/utils.rs
- tests/integration_test.rs
* delete a bunch of copy/paste code (let's slow down on that a little)
* add log dependency and inaugural 1 log message that helped me
* add env_logger dev-dependency so a developer can enable logging in tests if they want
* change SimpleCacheClientBuilder's new() to have the same semantics as our
pre-existing copy/paste method family for creating SimpleCacheClient. It is now lazy
and will allow endpoint resolution to only happen when an interaction is performed,
not eagerly (will create a data-only client more quickly now)
* change rust user agents: rust-sdk:VERSION is now the default, and we now have
rust-integration_test:VERSION and will soon have rust-cli:VERSION.
* fix up tests
> chore: clean up SimpleCacheClientBuilder

- src/response/list_cache_response.rs
- src/simple_cache_client.rs
- tests/integration_test.rs
The method `SimpleCacheClient::list_caches` supports pagination. It does this by means of
the parameter `next_token`: the client starts iteration with this set to
`None`, and ends when `MomentoCacheListResponse::next_token` is `None`.
Previously `MomentoCacheListResponse::next_token` was not optional, so
the end sentinel was empty string as opposed to `None`. This means the
client would have to start iteration with `None` and test for end
iteration comparing to empty string, which is confusing.
> chore: Align MomentoCacheListResponse and list_caches

- Cargo.toml
- src/momento/auth.rs
* add login message handler early-out ability to abort login when
browsers fail to open
* add session validity seconds to logged in message
* simplify login message handler callback type (`Fn` is not needed, `fn` is enough)
> chore: improve login()

- src/endpoint_resolver.rs
- src/jwt.rs
1. Hosted endpoint construction was incomplete and didn't generate correct urls.
2. The claim validation is based on the fields in `Claims`. So even if we require validation for `c` and `cp` claims, since these are Option<String> the validation succeeds. It required an additional check to enforce validation that `c` or `cp` claims must not be none when `momento_endpoint` is not specified.
> fix: Hosted Endpoint Construction and Claim validation

- .github/dependabot.yml
- .github/workflows/ci.yaml
- README.md
- examples/.gitignore
- examples/Cargo.toml
- examples/README.ja.md
- examples/README.md
- examples/src/main.rs
Added dependabot and updated the ci workflow as well.
> chore: move SDK examples from `client-sdk-examples`

- src/simple_cache_client.rs
Resolves the following clippy errors
```bash
error: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
--> src/simple_cache_client.rs:310:32
|
310 |                 NaiveDateTime::from_timestamp(res.expires_at as i64, 0),
|                                ^^^^^^^^^^^^^^
|
= note: `-D deprecated` implied by `-D warnings`
error: use of deprecated associated function `chrono::NaiveDateTime::from_timestamp`: use `from_timestamp_opt()` instead
--> src/simple_cache_client.rs:369:36
|
369 |                     NaiveDateTime::from_timestamp(signing_key.expires_at as i64, 0),
|                                    ^^^^^^^^^^^^^^
error: could not compile `momento` due to 2 previous errors
warning: build failed, waiting for other jobs to …
```
> chore: fix clippy warnings for timestamps parsing

- .github/workflows/cd.yml
- .github/workflows/ci.yaml
- README.md
- examples/src/main.rs
- src/endpoint_resolver.rs
- src/grpc/header_interceptor.rs
- src/jwt.rs
- src/simple_cache_client.rs
- tests/integration_test.rs
Resolves https://github.com/momentohq/client-sdk-rust/issues/61
Commit summary:
- chore: use integrated clippy warnings to check for .unwrap() calls. clean up .unwrap() usages.
- chore: update README with new code style guidelines
> chore: clean up .unwrap() uses and add clippy check to repo

- examples/README.md
- src/utils.rs
Prior to this commit, we did not have keepalives enabled for
idle gRPC channels.  As a result, any channel that was idle
for longer than NLB's idle connection timeout (about 6 minutes)
would be closed by the server, and the next attempt to use
it in the client would result in a transport error.
This commit enables keepalive for idle connections, sending
keepalive pings once every 2 minutes.  In local testing I observed
that a channel I left idle for over 6 minutes was still able
to be used successful on the next request after the idle period.
> fix: add keepalive settings to preserve idle connections

- src/simple_cache_client.rs
`cargo test` is failing because the doctests try and use a path that doesn't exist. Nothing in the doctest is actually using the imported item so I've just removed the import. This also fixes a type inference error in the same test.
> fix: remove import for non-existant path in doctest

- src/simple_cache_client.rs
As of now, the dictionary methods on `SimpleCacheClient` take the dictionary name as a `&str` and so they require that the dictionary name is valid UTF-8. As I understand it, momento has no such restriction and the protocol appears to allow any sequence of bytes as a name. This PR changes the dictionary argument to take anything that implements `MomentoRequest` and expands what implements `MomentoRequest` enough to cover all previous calling patterns.
This change came out of some comments on https://github.com/pelikan-io/pelikan/pull/12
This is a breaking change (although most users should be fine) so I have marked it as a feature.
> feat: allow dictionary client methods to take non-utf-8 dictionary names

- src/simple_cache_client.rs
This PR extends the use of `impl IntoBytes` from #88 to the rest of the functions within `SimpleCacheClient`.
> feat: use impl IntoBytes instead of generics in certain cases

- src/auth.rs
- src/lib.rs
- src/momento/mod.rs
Before this PR the auth module was in a nested momento module. So, to access it, you would need to look in `momento::momento::auth`. This is unnecessary and rather hard to use. This PR removes the nested momento module and drops the auth module into the crate root.
> feat: remove redundant nested momento module

- src/lib.rs
- src/simple_cache_client.rs
- tests/integration_test.rs
This PR makes the `simple_cache_client` module private and exports everything it used to export in the root module. `SimpleCacheClient` is the main type that users of the crate will be interacting with so it should really be in the root module. I have also re-exported `MomentoError` in the root module and added a `MomentoResult` type as a shorthand for `Result<T, MomentoError>`.
> feat: Move `SimpleCacheClient` and associated types to crate root

- src/simple_cache_client.rs
This commit attempts to make the internals of `SimpleCacheClient` a bit more idiomatic. The changes it makes are:
- Replace `Result<T, MomentoError>` with `MomentoResult<T>` everywhere it is used.
- Move boilerplate around preparing a `tonic::Request` into a helper method and use that method wherever applicable.
- Replace all uses of `drain(..)` with `into_iter()` and extract this out into a helper method.
> chore: clean up internals of SimpleCacheClient

- .github/workflows/cd.yml
- .github/workflows/ci.yaml
- .github/workflows/rust-clippy.yml
- Cargo.toml
- install_protoc.sh
- src/lib.rs
- src/preview/mod.rs
- src/preview/topics.rs
- src/simple_cache_client.rs
- src/utils.rs
Momento topics are currently under development but this first step
helps enable end-user experimentation with the types.
This adds a Pubsub client, complete with connect(), publish() and
subscribe().
subscribe() is the more interesting method, as it returns a
Subscription, which is a new kind of user-facing functionality for
our sdk. I've wrapped the protobuf types into simpler non-Optional
messages, marshaling some of their safe/default notions into what
they mean for a Momento subscription.
For context, the subscription usage looks like:
```rust
let client = Pubsub::connect(token, endpoint, Some("github-demo"))?;
let subscription = client
.subscribe(cache_name, topic, None)
.await?;
while let Some(item) = subscription.item().await? {
match item {
SubscriptionItem::Value(value) => match …
```
> feat: add feature preview for topics

- src/lib.rs
- src/simple_cache_client.rs
- src/utils.rs
- tests/integration_test.rs
This PR does two main things:
- Use Duration for all time-span values with the exception of ttl_minutes when creating a signing key.
- Introduce a TtlPolicy type and use that for all TTL parameters in cache client methods where a TTL was previously taken. This is similar to the CollectionTtl type in the JS SDK but I've used it a bit more widely.
This means that all time-spans now go through std's Duration type and there is now now way that users could, for example, pass seconds to a method that is expecting milliseconds. The one exception to this for create_signing_key. Duration has no from_minutes method and I felt that having the duration silently truncate down to the last minute would be too unintuitive if the only constructor is Duration::from_secs.
One thing to note is that now users …
> feat: Make TTL parameters use more idiomatic Rust

- Cargo.toml
- src/simple_cache_client.rs
This PR cleans up the documentation so that
1. It reads nicer from within rustdoc
2. It properly cleans up the cache even in the cases where the test case panics or errors out.
3. It uses `?` instead of `.expect` everywhere. I've added `anyhow` so that if debugging a test case becomes a necessary it is still possible to get a backtrace to the line on which the error was generated.
This PR doesn't hit all the doc comments. I will add a follow-up one which finishes up the rest of the methods on `SimpleCacheClient`.
> chore: clean up doc tests and avoid cache leaks on failure

- src/endpoint_resolver.rs
- src/response/error.rs
- src/simple_cache_client.rs
- tests/integration_test.rs
Clippy introduced some new warnings that are now causing CI to fail. This commit is just the result of having clippy fix them automatically.
> chore: fix clippy warnings

- Cargo.toml
- example/Cargo.toml
- src/simple_cache_client.rs
- test-util/Cargo.toml
- test-util/src/lib.rs
As per some offline discussions, this refactors some of the common boilerplate in the doctests out to a utility function in a utility crate. It ended up being simpler than I thought it would be. I have also changed the doctest for `delete` to use this as an example.
> chore: add a test-utils crate to make writing doctests easier

- src/simple_cache_client.rs
This PR extends the use of the `doctest` helper function from #111 to all doctests that interact with a specific cache. While going through the list I have also tried to make the doc tests more into examples that showcase behaviour rather than "here's one call to the function."
> chore: use test-utils crate in doctests and make examples more useful

- src/response/mod.rs
- src/simple_cache_client.rs
As in the title. I have included documentation and an example for each one. The one operation I implemented which was not in the protocol was `list_set` as a wrapper around `list_concat_front` since it made all the doctests much easier to understand.
> chore: implement all SDK list operations

- src/response/mod.rs
- src/simple_cache_client.rs
As in the title. I have also added aliases here to match those used in the .NET SDK - although I've still kept `set_union` and `set_difference` methods as the main ones with example documentation.
I've also made an attempt to make the doctest behave better in the face of assertion failures.
> chore: Add support for SDK set difference command

- src/simple_cache_client.rs
This adds a `list_erase_many` which accepts multiple ranges. I didn't think that I would need this but then I immediately found a use case when looking at the redis commands so in it goes.
> chore: Implement multiple-range list_erase variant

- Cargo.toml
- src/preview/topics.rs
This adds support for heartbeats that will be rolled out more broadly
soon. We'll need to be able to accept these messages and allow the
subscription to continue.
> chore: Handle heartbeats in topics

- src/response/flush_cache_response.rs
- src/response/list_cache_response.rs
- src/response/mod.rs
- src/simple_cache_client.rs
- tests/integration_test.rs
I have some thoughts on tweaking some of the APIs in this repo a bit before 1.0 now that I have gotten to look at them a bit, so this might not be the final API for flush cache; but this unblocks us for getting it into the CLI, which is something customers are wanting / needing, so I would like to move forward with this API for now.
> feat: add support for flush cache API

- src/lib.rs
- src/requests/generate_api_token_request.rs
- src/requests/mod.rs
- src/simple_cache_client.rs
The `generate_api_token` request takes in an `Expiry` enum. This enum comes directly from the client protos, and without publishing the enum and its values, a customer cannot call the `generate_api_token`.
https://github.com/momentohq/client-sdk-rust/blob/main/src/simple_cache_client.rs#L2266
> fix: publish Expires, Expiry, Never from generate token protos

- src/simple_cache_client.rs
- src/utils.rs
- test-util/src/lib.rs
- tests/integration_test.rs
Ongoing auth work has updated the token used by this test runner.
These tests no longer work and block updates to the sdk. Their
asserts should be restored in one way or another, but they need
to not block publish.
Also sneaking in a small update to the keepalive ping timer to help
clarify debug log messages on momento-cli.
> fix: disable integration tests

- src/lib.rs
- src/response/cache_sorted_set_fetch_response.rs
- src/simple_cache_client.rs
Adds a function to the simple cache client to fetch elements of a sorted set selecting them by index (rank).
> feat: add sorted_set_fetch_by_index

- src/simple_cache_client.rs
Adds a simple form of sorted_set_fetch_by_score that allows fetching a range of elements from a sorted set, selecting by score.
> feat: add sorted_set_fetch_by_score

- Cargo.toml
- src/simple_cache_client.rs
- src/utils.rs
Also removes generate_api_token temporarily, as it is currently not
supported in the way this sdk has it.
> chore: update protos

- .github/workflows/cd.yml
Disable releasing on merge to main. We are putting substantial work into the SDK and don't need to create a ton of new releases. We will add release-please at a later time.
> chore: disable releasing on every merge to main

- src/response/list_cache_response.rs
- src/response/list_signing_keys_response.rs
- src/simple_cache_client.rs
- tests/integration_test.rs
Remove the next_token argument from list_caches and list_signing_keys. It isn't used by the back end and clutters the function signature.
Add a delete_cache to an integration test that was missing one. The tests may still leak caches if the tests fail before getting to the delete cache statement at the end. More comprehensive protection will follow.
> chore: remove next token from list_caches and list_signing_keys

- src/simple_cache_client.rs
As we experiment with different ways to express the requests
and optional arguments, some of the request preparation may
move outside of the SimpleCacheClient class. The prep_request
fn used by all of the request API fns was a member fn of
SimpleCacheClient, even though it didn't reference `self`. This
commit moves it out of the struct and into a regular function
so that it will be accessible from outside SimpleCacheClient.
This will allow us to more freely experiment with creating
requests from other places in the code.
> chore: move prep_request out of SimpleCacheClient

- .github/workflows/cd.yml
- .github/workflows/ci.yaml
- src/cache_client.rs
- src/lib.rs
- src/requests/cache/mod.rs
- src/requests/cache/set_add_elements.rs
- src/requests/mod.rs
- src/simple_cache_client.rs
This is a prototype of the new API that Kenny, Nate and I have been discussing. In this model we define a Request and a Response struct for each API. The Request structs can be used as builders, to support optional arguments and future additions to the API. The CacheClient exposes the simplest possible syntax for each API, with no optional arguments provide, and implements that by instantiating one of the Request structs.
The Request trait requires each Request type to implement a `send` function, to do the work of sending the request. This will allow us to keep the logic for the implementation details of each API in its own struct, rather than having all of the implementations live direction in `CacheClient`.
`CacheClient` also provides a `send_request` fn that can be called directly, …
> feat: prototype of new API using requests as builders

- src/cache_client.rs
- src/config/configuration.rs
- src/config/configurations.rs
- src/config/grpc_configuration.rs
- src/config/mod.rs
- src/config/transport_strategy.rs
- src/lib.rs
- src/requests/cache/set_add_elements.rs
- src/simple_cache_client.rs
- src/utils.rs
Add a nested configuration object in the style of the other SDKs.
Add pre-built configurations for different environments.
Plumb the config object into the client, connection, and existing call.
> feat: add a configuration object for the cache client

- .github/workflows/ci.yaml
- Cargo.toml
- scripts/test-setup.rs
- scripts/test-teardown.rs
- src/cache_client.rs
- src/requests/cache/create_cache.rs
- src/requests/cache/delete_cache.rs
- src/requests/cache/mod.rs
- src/requests/cache/set_add_elements.rs
- src/requests/cache/sorted_set_fetch_by_rank.rs
- src/requests/cache/sorted_set_fetch_by_score.rs
- src/requests/cache/sorted_set_put_element.rs
- src/requests/cache/sorted_set_put_elements.rs
- src/response/cache/mod.rs
- src/response/cache/sorted_set_fetch.rs
- src/response/mod.rs
- test-util/src/lib.rs
- tests/cache_sorted_set_tests.rs
- tests/cache_test_state.rs
Add sorted set put element(s), fetch by rank, and fetch by score.
Add create and delete cache methods for testing.
Add test setup and teardown scripts so that we can guarantee the cache exists for doc and integration tests, and ensure it is deleted after they run.
Call the setup and teardown scripts in github ci.
> feat: Add sorted set put and fetch functions

- example/Cargo.toml
- example/src/main.rs
- example/src/readme.rs
- src/cache_client.rs
- src/credential_provider.rs
- src/lib.rs
- src/preview/topics.rs
- src/requests/cache/basic/get.rs
- src/requests/cache/basic/mod.rs
- src/requests/cache/basic/set.rs
- src/requests/cache/mod.rs
- src/requests/cache/set/mod.rs
- src/requests/cache/set/set_add_elements.rs
- src/requests/cache/sorted_set/mod.rs
- src/requests/cache/sorted_set/sorted_set_fetch_by_rank.rs
- src/requests/cache/sorted_set/sorted_set_fetch_by_score.rs
- src/requests/cache/sorted_set/sorted_set_put_element.rs
- src/requests/cache/sorted_set/sorted_set_put_elements.rs
- src/response/cache/sorted_set_fetch.rs
- src/simple_cache_client.rs
- src/utils.rs
- test-util/src/lib.rs
- tests/cache_sorted_set_tests.rs
- tests/integration_test.rs
The main goal of this PR is to get us closer to having a good example code snippet in the readme.ts file. There were a few things I discovered that we need along the way toward that, so this PR tries to bite off a few of them:
* We need `get` and `set`, so those are added in this PR.
* The credential provider builder pattern didn't seem quite as ergonomic as some of our newer ones (CacheClient/requests), and wasn't consistent with the direction of them, so I tweaked a few things to try to move it in that direction. This is not the final state of this, I intend to do at least one more pass to try to make sure that the builders/constructors for client, requests, cred providers, and configs are as consistent as possible, but this is an interim step.
* I also removed/commented out the support …
> feat: add get/set to CacheClient to support readme.ts example

- README.template.md
- example/Makefile
- example/src/bin/readme.rs
- example/src/main.rs
- example/src/readme.rs
Prior to this commit, there was a bug in the Makefile that was preventing the examples from actually getting built in CI.
Also there were several things in the examples that were out of date and no longer compile, so this commit fixes them.
NOTE: in an earlier PR, I accidentally committed a change that makes the examples point to `..` to access the SDK, instead of using a release. I will fix this in a future commit but will be easier to do that once we have the release process working again.
> chore: fix and build examples

- src/cache_client.rs
- src/config/configuration.rs
- src/credential_provider.rs
- src/requests/cache/basic/get.rs
- src/requests/cache/basic/set.rs
- src/requests/cache/set/set_add_elements.rs
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/737
Replaces cache client creation in examples with hidden calls to `create_doctest_cache_client` to better focus the examples on how to use the APIs.
Used `cargo doc --open` to check formatting and make additional whitespace / extra braces / miscellaneous edits.
> chore: audit doctests for cache client creation

- src/cache_client.rs
- src/credential_provider.rs
- src/requests/cache/basic/get.rs
- src/requests/cache/basic/set.rs
- src/requests/cache/create_cache.rs
- src/requests/cache/delete_cache.rs
- src/requests/cache/set/set_add_elements.rs
- src/requests/cache/sorted_set/sorted_set_fetch_by_rank.rs
- src/requests/cache/sorted_set/sorted_set_fetch_by_score.rs
- src/requests/cache/sorted_set/sorted_set_put_element.rs
- src/requests/cache/sorted_set/sorted_set_put_elements.rs
- src/requests/generate_api_token_request.rs
- src/requests/mod.rs
This commit attempts to take a pass through all of the public APIs and find places where we were unnecessarily being too rigid about what flavor of String we accept. We use `impl Into<String>` as the argument type in most places now, which means that callers can pass us either `&str` or `String`.
> feat: use impl Into<String> on most public APIs

- .github/workflows/on-pull-request.yml
- Makefile
- src/requests/cache/list_caches.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/199
Adds new Makefile target to build the docs with a flag set to fail when there are warnings. 
Adds new `on-pull-request` workflow step to build the docs with that Makefile target.
First commit should fail with docs warning, second commit should fix the issue and the build should pass.
> chore: make build fail when there are docs warnings

- src/cache_client.rs
- tests/cache_sorted_set.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/192 
As discussed with Chris and Michael, it's pretty likely users will call fetch by rank to paginate through their sorted set, whereas we can't easily predict what arguments they'll want to set for fetch by score. Hence we're adding the start_rank and end_rank optional arguments to the fetch by rank API as required arguments to differentiate it from fetch by score.
> feat: add start_rank and end_rank as optional arguments to SortedSetFetchByRank

- src/cache_client.rs
- src/requests/cache/basic/get.rs
- src/requests/cache/basic/set.rs
- src/requests/cache/create_cache.rs
- src/requests/cache/delete_cache.rs
- src/requests/cache/list_caches.rs
- src/requests/cache/set/set_add_elements.rs
- src/requests/cache/sorted_set/sorted_set_fetch_by_rank.rs
- src/requests/cache/sorted_set/sorted_set_fetch_by_score.rs
- src/requests/cache/sorted_set/sorted_set_fetch_response.rs
- src/requests/cache/sorted_set/sorted_set_put_element.rs
- src/requests/cache/sorted_set/sorted_set_put_elements.rs
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/724 and general docs improvements.
Code examples in the `cache_client.rs` file now show examples of `cache_client.*` calls but link to the specific request objects that show examples of `send_request` calls.
With the exception of the `cache_client::get` example, I removed the assert statements in favor of pattern matching examples. A couple of the pattern matching statements (`deleteCache` and `set`) show how to handle specific errors like `NotFoundError`. 
Not specifically attached to the style of the code examples, so if it's more idiomatic to show a simple API call with an `await?` at the end rather than using a `match` statements, I can change that.
> chore: improve docs, replace asserts with pattern matching, reduce duplication of code examples

- src/requests/errors.rs
- tests/cache_control.rs
- tests/cache_sorted_set.rs
Trying to revise existing tests to better align what we want for best practices:
* avoid using `unwrap`, use `?` instead as per the [contributing docs](https://github.com/momentohq/client-sdk-rust/blob/main/CONTRIBUTING.md)
* tests should return a `MomentoResult` (see [this comment](https://github.com/momentohq/client-sdk-rust/pull/209#discussion_r1542177360))
* avoid `clone()`-ing things unnecessarily
* ran into an issue with `assert!(matches!(...))` not actually working as expected with strings (see [this comment](https://github.com/momentohq/client-sdk-rust/pull/217#issuecomment-2043730017)). Preferring to compare `MomentoErrorCode`s instead when expecting errors
> chore: refactor tests for better consistency, more accurate asserts

- src/cache/requests/scalar/delete.rs
- src/cache/requests/scalar/get.rs
- src/cache/requests/scalar/increment.rs
- src/cache/requests/scalar/item_get_type.rs
- src/cache/requests/scalar/key_exists.rs
- src/cache/requests/scalar/keys_exist.rs
- src/cache/requests/scalar/set.rs
- src/cache/requests/set/set_add_elements.rs
- src/cache/requests/sorted_set/sorted_set_fetch_by_rank.rs
- src/cache/requests/sorted_set/sorted_set_fetch_by_score.rs
- src/cache/requests/sorted_set/sorted_set_put_element.rs
- src/cache/requests/sorted_set/sorted_set_put_elements.rs
- src/simple_cache_client.rs
- src/utils.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/220 
Pulls `prep_request_with_timeout` and `request_meta_data` into `utils`, but leaves `prep_request` in `simple_cache_client` so that can be removed along with `simple_cache_client`.
We'll be using only `prep_request_with_timeout` when implementing new APIs.
> fix: move prep_request_with_timeout into utils

- test-util/src/lib.rs
- test-util/src/test_utils.rs
- tests/cache_control.rs
- tests/cache_scalar.rs
- tests/cache_sorted_set.rs
- tests/old/integration_test.rs
This commit does two things:
1. Adds a test utility function to DRY up all the places where
we were creating UUIDs to create unique strings, and
2. In all the places where the tests were doing `&*` or `&**` to
get access to a `&str` to pass to the APIs under test, we now
just create two variables. The first variable is a `String`,
so that the lifetime / ownership of the `String` extends through
the end of the function; the second variable is a `&str` acquired
via `&str`. This can be passed to the APIs under test as many times
as possible without a "move" causing a compile failure, and prevents
the need to do `.clone()` or `.as_str()` at every call site.
> chore: minor test cleanups

- tests/cache_control.rs
- tests/cache_item.rs
- tests/cache_key_exists.rs
- tests/cache_scalar.rs
- tests/cache_sorted_set.rs
In order for developers to easily compare integration test coverage vs
the JS suite, a package with known well coverage, we organize the
integration tests to mirror those.
Specifically we chose filenames that are similar to those used in the
JS integration test repos. Then, in order to parallel the `describe`
blocks, we introduce a `mod` for each describe. The individual tests
therein should be parallel to the `it` calls in the JS repo.
We've organized the data plane commands into the following
files:
- cache_scalar.rs: commands where the value type is scalar
- cache_sorted_set.rs: commands where the value type is sorted set
- cache_key_exists.rs: commands to test existence of a cache key
- cache_item.rs: commands that apply to a cache item irrespective of
type.
Previously the tests under …
> test: organize integration tests following js integration tests

- Cargo.toml
- src/cache/requests/sorted_set/sorted_set_fetch_by_rank.rs
- src/cache/requests/sorted_set/sorted_set_fetch_by_score.rs
- src/simple_cache_client.rs
We'll need a newer version of the client protos dependency to implement the `SetIf*` APIs
> chore: update client protos dependency

- tests/cache/item.rs
- tests/cache/mod.rs
- tests/cache/ttl.rs
Two PRs went in at the same time: the test refactor and the cache ttl
tests. Because of this the ttl tests were not in the new place. This
PR corrects that.
> test: put ttl tests in new structure

- src/cache/requests/sorted_set/sorted_set_fetch_response.rs
- test-util/src/test_data.rs
- tests/cache/scalar.rs
- tests/cache/sorted_set.rs
We audit test coverage for `get`, `set`, and `sorted sets` and add tests as needed. We also implement traits and conveniences that will make future integration test authorship easier. In particular:
- For each test data type, we implement the `From` trait paired with the corresponding cache hit response. That way we can use the test data directly in an assertion without the need to massage it in the right form.
- We extract asserting a collection fetch is equal to test data. Both unpacking the actual result, massaging the expected reuslt, and comparing contain a lot of boilerplate. The sorted set tests demonstrate this pattern.
> test: more scalar coverage and test conveniences

- src/cache/mod.rs
- src/cache/requests/list/list_concatenate_back.rs
- src/cache/requests/list/list_concatenate_front.rs
- src/cache/requests/list/list_fetch.rs
- src/cache/requests/list/list_length.rs
- src/cache/requests/list/list_pop_back.rs
- src/cache/requests/list/list_pop_front.rs
- src/cache/requests/list/list_remove_value.rs
- src/cache/requests/list/mod.rs
- src/cache/requests/mod.rs
- src/cache_client.rs
- test-util/src/lib.rs
- test-util/src/test_data.rs
- tests/cache/list.rs
- tests/cache/mod.rs
Addresses #165 
Prioritized getting these APIs implemented:
- listConcatenateBack
- listConcatenateFront
- listFetch
- listLength
- listPopBack
- listPopFront
- listRemoveValue
listPushFront and listPushBack were also implemented in the simple_cache_client but seemed less urgent to include them here since the same functionality can be done using the concatenate methods.
> feat: add list collection

- src/cache/requests/dictionary/dictionary_fetch.rs
- src/cache/requests/sorted_set/sorted_set_fetch_response.rs
- src/cache_client.rs
- test-util/src/test_data.rs
- tests/cache/sorted_set.rs
In order to be in line with other our standard, we rename the hit
field from elements to value.
In addition we document `SortedSetFetch` and correct the `TryFrom`
on `SortedSetElements` to derive `From` instead.
> refactor: rename sorted set fetch hit elements field and document response

- src/cache/requests/dictionary/dictionary_fetch.rs
- src/cache/requests/list/list_fetch.rs
- src/cache/requests/list/list_length.rs
- src/cache/requests/list/list_pop_back.rs
- src/cache/requests/list/list_pop_front.rs
- src/cache/requests/scalar/decrease_ttl.rs
- src/cache/requests/scalar/get.rs
- src/cache/requests/scalar/increase_ttl.rs
- src/cache/requests/scalar/item_get_ttl.rs
- src/cache/requests/scalar/item_get_type.rs
- src/cache/requests/scalar/key_exists.rs
- src/cache/requests/scalar/set_if_absent.rs
- src/cache/requests/scalar/set_if_absent_or_equal.rs
- src/cache/requests/scalar/set_if_equal.rs
- src/cache/requests/scalar/set_if_not_equal.rs
- src/cache/requests/scalar/set_if_present.rs
- src/cache/requests/scalar/set_if_present_and_not_equal.rs
- src/cache/requests/scalar/update_ttl.rs
- src/cache/requests/sorted_set/sorted_set_fetch_response.rs
- src/errors.rs
- src/utils.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/239
Also caught a couple instances where None was being caught but returned a Miss; updated those to return UnknownError as well
> fix: replace usage of unreachable macro with returning an UnknownError

- CONTRIBUTING.md
- Makefile
- tests/cache/control.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/238 
Without limiting number of threads, Michael saw lots of `setIf` test failures, whereas on my machine I saw lots of `list` test failures. I think this is because the `flushCache` test was causing a race condition since it operates on the same test cache as the other tests, but it's nondeterministic when it would kick in.
I used the `#[ignore]` as per the [Rust docs](https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested) and added another line to the `test-integration` Makefile target to run the `flushCache` test first, then all the other tests. This allows us to run all the other tests with no thread limitation once again.
I opted to adjust the ordering of tests rather …
> chore: run flush cache test separately from other tests

- src/cache/requests/dictionary/dictionary_get_fields.rs
- src/cache/requests/dictionary/dictionary_remove_fields.rs
- src/cache/requests/list/list_concatenate_back.rs
- src/cache/requests/list/list_concatenate_front.rs
- src/cache/requests/scalar/keys_exist.rs
- src/cache/requests/set/set_add_elements.rs
- src/cache/requests/sorted_set/sorted_set_remove_elements.rs
- src/cache_client.rs
- src/lib.rs
- src/simple_cache_client.rs
- src/utils.rs
- tests/cache/dictionary.rs
- tests/cache/key_existence.rs
- tests/cache/list.rs
Addresses #245 
First pass at abstracting the `Vec<IntoBytes>` instances into `IntoBytesIterable`
Also moved `IntoBytes` out of the `simple_cache_client` file and into `utils` instead
> chore: extract lists of IntoBytes into an IntoBytesIterable trait

- src/cache/mod.rs
- src/cache/requests/dictionary/dictionary_remove_field.rs
- src/cache/requests/dictionary/mod.rs
- src/cache_client.rs
- tests/cache/dictionary.rs
Add cache client command for `dictionary_remove_field`, request and
response types, integration tests, and docs.
> feat: implement dictionary_remove_field

- example/Cargo.toml
- example/src/main.rs
As part of the cutover to the new SDK, we port the example from using the old client to the new one.
> chore: port example to new sdk

- CONTRIBUTING.md
- Makefile
- tests/cache/control.rs
Addresses #271 
Creating a separate cache for the flush_cache test so that we reserve the `--ignored` flag for test we may actually want to ignore down the road
> chore: flush_cache test should create own cache

- src/topics/config/configuration.rs
- src/topics/config/configurations.rs
- src/topics/config/mod.rs
- src/topics/messages/mod.rs
- src/topics/messages/momento_request.rs
- src/topics/messages/publish.rs
- src/topics/messages/subscribe.rs
- src/topics/messages/subscription.rs
- src/topics/mod.rs
- src/topics/topic_client.rs
- src/topics/topic_client_builder.rs
Made edits based on https://github.com/momentohq/client-sdk-rust/pull/274
Adding integration tests for topics will require setting up a shared topics client, created a separate ticket for that: https://github.com/momentohq/client-sdk-rust/issues/277
> feat: update the topic client for consistency with cache client

- src/utils.rs
Broadens the trait implementation for `IntoBytesIterable` from
`Vec<T>` to `IntoIterator<Item = T>` for use on both dynamically
allocated and static arrays.
> chore: allow `IntoBytesIterable` on statically allocated arrays

- README.template.md
- example/Cargo.toml
- example/src/bin/docs_examples.rs
- example/src/bin/topics.rs
- src/topics/messages/publish.rs
- src/topics/messages/subscribe.rs
- src/topics/messages/subscription.rs
- src/topics/mod.rs
- src/topics/topic_client.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/275
- rename SubscriptionRequest -> SubscribeRequest for consistency
- update readme template to include installing tokio and futures
- make sure all Subscription-related objects are exported
- add more examples in docstrings
- update dev docs examples
- add topics example file
> feat: TopicClient follow-up revisions"

- scripts/test-setup.rs
- scripts/test-teardown.rs
- src/cache/config/configuration.rs
- src/cache/config/configurations.rs
- src/topics/config/configuration.rs
- src/topics/config/configurations.rs
- src/topics/messages/publish.rs
- src/topics/messages/subscribe.rs
- src/topics/messages/subscription.rs
- src/topics/topic_client.rs
- test-util/src/cache_test_state.rs
- test-util/src/test_utils.rs
Groups pre-built configs into structs. Previously they were mods, which, while syntactically legal, differs from the patterns in our SDKs and other types in this one.
In the first iteration, I considered making a trait to capture the various versions we would expose (eg `latest`, `v1`), but found consuming the trait too much friction to just import a single config.
> refactor: declare structs for pre-built configurations

- src/cache/cache_client.rs
- src/cache/messages/dictionary/dictionary_fetch.rs
- src/cache/messages/dictionary/dictionary_get_field.rs
- src/cache/messages/dictionary/dictionary_get_fields.rs
- src/cache/messages/dictionary/dictionary_increment.rs
- src/cache/messages/dictionary/dictionary_length.rs
- src/cache/messages/dictionary/dictionary_remove_field.rs
- src/cache/messages/dictionary/dictionary_remove_fields.rs
- src/cache/messages/dictionary/dictionary_set_field.rs
- src/cache/messages/dictionary/dictionary_set_fields.rs
- src/cache/mod.rs
- tests/cache/dictionary.rs
Adds the suffix `Response` to all dictionary response types to code and docstrings.
Work towards #285
> feat: add response suffix to dictionary response types

- src/cache/cache_client.rs
- src/cache/messages/list/list_concatenate_back.rs
- src/cache/messages/list/list_concatenate_front.rs
- src/cache/messages/list/list_fetch.rs
- src/cache/messages/list/list_length.rs
- src/cache/messages/list/list_pop_back.rs
- src/cache/messages/list/list_pop_front.rs
- src/cache/messages/list/list_remove_value.rs
- src/cache/mod.rs
- test-util/src/test_data.rs
- tests/cache/list.rs
Adds the suffix Response to all dictionary response types to code and docstrings.
Work towards #285
> feat: add response suffix to list types

- Makefile
- example/Cargo.toml
- example/src/bin/basic.rs
- example/src/bin/docs_examples.rs
- example/src/bin/readme.rs
- example/src/bin/topics.rs
- src/credential_provider.rs
Implements Display for CredentialProvider to ensure that we redact
the auth token.
Also updates the examples to the new struct names for the
cred providers.
> fix: impl Display for CredentialProvider

- src/cache/cache_client.rs
- src/cache/messages/sorted_set/sorted_set_fetch_by_rank.rs
- src/cache/messages/sorted_set/sorted_set_fetch_by_score.rs
- src/cache/messages/sorted_set/sorted_set_fetch_response.rs
- src/cache/messages/sorted_set/sorted_set_get_rank.rs
- src/cache/messages/sorted_set/sorted_set_get_score.rs
- src/cache/messages/sorted_set/sorted_set_length.rs
- src/cache/messages/sorted_set/sorted_set_put_element.rs
- src/cache/messages/sorted_set/sorted_set_put_elements.rs
- src/cache/messages/sorted_set/sorted_set_remove_elements.rs
- src/cache/mod.rs
- test-util/src/test_data.rs
- tests/cache/sorted_set.rs
Adds the suffix Response to all sorted set types in code and docstrings.
Work towards https://github.com/momentohq/client-sdk-rust/issues/285
> feat: add response suffix to sorted set types

- src/cache/cache_client.rs
- src/cache/messages/create_cache.rs
- src/cache/messages/delete_cache.rs
- src/cache/messages/flush_cache.rs
- src/cache/messages/list_caches.rs
- src/cache/mod.rs
- test-util/src/cache_test_state.rs
- tests/cache/control.rs
Adds the suffix Response to cache control types in code and docstrings.
Work towards https://github.com/momentohq/client-sdk-rust/issues/285
> feat: add response suffix to control commands

- Makefile
- scripts/test-teardown.rs
- src/cache/messages/data/dictionary/dictionary_get_field.rs
- src/cache/messages/data/list/list_fetch.rs
- src/cache/messages/data/list/list_pop_back.rs
- src/cache/messages/data/list/list_pop_front.rs
- src/cache/messages/data/set/set_fetch.rs
- src/cache/messages/data/sorted_set/sorted_set_get_score.rs
- src/grpc/header_interceptor.rs
- test-util/src/cache_test_state.rs
- test-util/src/test_utils.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/279
Added the clippy rule Dylan recommended and refactored as needed. Had to revise the `lint` Makefile and add `#[allow(clippy::expect_used)]` in several places to omit test-related files from the rule as we _do_ want the tests to panic if something goes wrong.
Current implementations of `From` and `TryFrom` are fine upon inspection.
> chore: add lint rule to check usage of expect

- src/errors.rs
- src/topics/config/configuration.rs
- src/topics/messages/momento_request.rs
- src/topics/messages/publish.rs
- src/topics/messages/subscribe.rs
- src/topics/messages/subscription.rs
- src/topics/mod.rs
- src/topics/topic_client.rs
- tests/topics/pubsub.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/299
- The basic `subscribe` method returns only `SubscriptionValue`s now (only binary or string values, not discontinuities)
- Removed the discontinuity error and `TryFrom` that had been used in a test
- Renamed `TopicPublish` to `TopicPublishResponse` for consistency with the rest of the SDK
- Updated doctests and filled in more missing docstrings related to topics
> feat: basic subscriptions should return only SubscriptionValues

- src/cache/messages/control/list_caches.rs
- src/cache/messages/data/dictionary/dictionary_fetch.rs
- src/cache/messages/data/dictionary/dictionary_get_field.rs
- src/cache/messages/data/dictionary/dictionary_get_fields.rs
- src/cache/messages/data/list/list_fetch.rs
- src/cache/messages/data/list/list_pop_back.rs
- src/cache/messages/data/list/list_pop_front.rs
- src/cache/messages/data/scalar/get.rs
- src/cache/messages/data/set/set_fetch.rs
- src/cache/messages/data/sorted_set/sorted_set_fetch_response.rs
- src/cache/mod.rs
- test-util/src/test_data.rs
- tests/cache/control.rs
Renames various collection inner value types to `Value` and updates conversion traits.
None of these types (except one) need to be rolled up to `momento::cache`. They are either only used in:
- doctests, or
- integration tests
In both of those cases we can avoid using them by using various `From` and `Default` traits. We keep the types publicly visible so a user can still `use` them, albeit with a longer fully qualified name.
The only inner value type we roll up to `momento::cache` is `SortedSetElements`. We still roll this one up since as user may want to pass a `Vec` of these to a `SortedSetPutElementsRequest`.
Closes #285
> refactor: rename various response value types to `Value` and update traits

- src/cache/cache_client.rs
Addresses an item in https://github.com/momentohq/client-sdk-rust/issues/284
We already have docstrings showing how to use `match` or `try_into` on responses, this just adds links from the `cache_client` method docstrings to the response docstrings to make it more obvious if users are curious.
> chore: add links to response docstrings showing how to handle hits/misses

- src/cache/messages/data/sorted_set/sorted_set_length.rs
- src/utils.rs
- tests/cache/dictionary.rs
- tests/cache/item.rs
- tests/cache/key_existence.rs
- tests/cache/scalar.rs
- tests/cache/ttl.rs
Addresses https://github.com/momentohq/client-sdk-rust/issues/270 
It seems like we used `expect` where appropriate for the most part, added a few more.
This PR also adds informative failure messages to the `assert!` statements.
> chore: improve error messages in tests

- Cargo.toml
- src/cache/messages/data/scalar/get.rs
- src/utils.rs
Presents a pattern we can use to get debug and display for response types.
Because our cache stores data as bytes, when users build a request or receive a response, they get back a wrapper around `Vec<u8>` of some form. This may be a `Vec<u8>` directly or another data structure like a `HashMap` or another `Vec`, for example.
In order to aid debugging and printing, we provide debug and display trait implementations that attempt to interpret and display the bytes as strings. There are two aspects to this:
1. For each `Value` type in a response, we manually implement `std::fmt::Debug` and `std::fmt::Display`. We have authored utility functions in `utils::fmt` to aid with this. See the `get_response::Value` implementation.
2. We auto-derive `Debug` and `Display` for the response type …
> feat: implement custom debug and display traits for byte-array types

- test-util/src/test_utils.rs
Changes the doctest signature to fix clippy error regarding trait
bounds.
The previous version started failing on GitHub on the `lint` make target
but continues to succeed locally. I have verified my `cargo` and `clippy`
versions are identical to those used in the GitHub Action runner. 
I do not know why it does not fail locally, and I have exhausted my timebox.
This fix directly addresses the clippy error on GitHub and has appeased it.
Closes #326
> fix: clippy error on gh with doctest signature

- .github/workflows/rust-clippy.yml
v1 of upload-sarif is [deprecated](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/). We upgrade to v2.
```
[Run rust-clippy analyzing](https://github.com/momentohq/client-sdk-rust/actions/runs/9103552264/job/25025625153#step:6:9)
This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
```
> chore: upgrade codeql action upload sarif version

- .github/workflows/on-pull-request.yml
Previously we ran on `macos` to sidestep timeouts of uncertain origin on `ubuntu-22.04` + GitHub's Azure runners. This has resolved on `ubuntu-24.04`
> chore: run ci on ubuntu-24.04

- src/cache/messages/data/dictionary/dictionary_fetch.rs
- src/cache/messages/data/scalar/get.rs
- src/utils.rs
I wanted to play with what it would feel like to implement Debug for
other response types. In this PR I implemented it for DictionaryFetchResponse.
However, along the way I found that it was really hard to get the pretty-print
indenting correct when we are manually calling `Formatter::write*`; it's much
easier if we can stick to calling the `Formatter::debug_*` variants. So
I refactored the `fmt` utils a bit, to give us a `DebuggableValue` trait. This
trait provides an `as_debuggable_value` function for vec<u8>, String, and &str.
The implementations of Debug for the response Value structs can just use this
to get an instance of DebuggableValue, and then use `Formatter.debug_*` to
debug whatever collection type is appropriate.
> chore: implement Debug for DictionaryFetchResponse, tweak debug fmt utils

- .github/workflows/on-push-to-main.yml
- Makefile
In a recent commit we moved the sdk code into a subdir to avoid
Cargo workspace collisions. That caused the publish to fail
because it expects a README to exist in the directory we're publishing
from.
This commit moves the publish logic into the Makefile to centralize it
like the other build tasks, and adds a step to copy the README from
the parent directory before we execute the publish.
> fix: publish task broken with sdk subdir

- Makefile
- sdk/.gitignore
In an earlier commit we moved the sdk to a subdir to prevent issues
with Cargo workspaces related to having a Cargo.toml file in a
parent dir of the examples.
We are now trying to publish the SDK from this new `sdk` subdir,
but it needs a README.md, so we are copying that file from the root
dir of the github repo into the `sdk` dir prior to publishing.
However, the `cargo publish` operation doesn't allow publishing
from a dirty git working tree. This commit adds the README to
the sdk/.gitignore so that the tree won't be flagged as dirty.
Another option we could consider in the future would be to add
another README generator action to the github actions, to just
generate a second copy of the root README and output it to the
`sdk` directory.
> chore: add sdk/README to gitignore to prevent attempt to publish from dirty tree

- Makefile
- sdk/src/cache/messages/data/dictionary/dictionary_increment.rs
- sdk/src/cache/messages/data/dictionary/dictionary_set_field.rs
- sdk/src/cache/messages/data/dictionary/dictionary_set_fields.rs
- sdk/src/cache/messages/data/list/list_concatenate_back.rs
- sdk/src/cache/messages/data/list/list_concatenate_front.rs
- sdk/src/cache/messages/data/list/list_fetch.rs
- sdk/src/cache/messages/data/list/list_push_back.rs
- sdk/src/cache/messages/data/list/list_push_front.rs
- sdk/src/cache/messages/data/scalar/increment.rs
- sdk/src/cache/messages/data/scalar/set.rs
- sdk/src/cache/messages/data/scalar/set_if_absent.rs
- sdk/src/cache/messages/data/scalar/set_if_absent_or_equal.rs
- sdk/src/cache/messages/data/scalar/set_if_equal.rs
- sdk/src/cache/messages/data/scalar/set_if_not_equal.rs
- sdk/src/cache/messages/data/scalar/set_if_present.rs
- sdk/src/cache/messages/data/scalar/set_if_present_and_not_equal.rs
- sdk/src/cache/messages/data/set/set_add_elements.rs
- sdk/src/cache/messages/data/sorted_set/sorted_set_fetch_by_rank.rs
- sdk/src/cache/messages/data/sorted_set/sorted_set_fetch_by_score.rs
- sdk/src/cache/messages/data/sorted_set/sorted_set_put_element.rs
- sdk/src/cache/messages/data/sorted_set/sorted_set_put_elements.rs
Per user feedback, we should support `Option` parameters on builders when the parameter is actually optional. Currently the SDK expects mandatory values for those builder functions, even when the parameter is actually optional.
To do this, where applicable, we change each parameter type to be `impl Into<Option<>>` which is backwards compatible.
Closes #356
> chore: make optional things optional on request builders

- example/rust/Cargo.lock
- example/rust/Cargo.toml
- example/rust/src/bin/storage.rs
- sdk/src/errors.rs
- sdk/src/storage/messages/data/get.rs
This is a POC for addressing some of the things that we ran into in the other SDKs; namely:
1. Split up NotFound errors into distinct categories
2. Change GetResponse value to Optional, to allow us to distinguish between NotFound and WrongType
Also removes the inner `Success` enum value from the GetResponse because it was making it harder to work with the success case, and in the Cache client, we don't use enums when we only have a single response type.
Open to feedback on all of the above.
> feat: improve NotFound handling, return Optional for storage get

- .github/workflows/on-pull-request.yml
- sdk/Cargo.lock
- sdk/Cargo.toml
- sdk/src/credential_provider.rs
Remove jwt support from the credential provider. They don't work correctly for storage and haven't been used for some time.
Remove now unneeded jsonwebtoken dependency.
> chore: remove legacy jwt token support

- sdk/Cargo.lock
- sdk/src/errors.rs
- sdk/src/storage/messages/control/create_store.rs
- sdk/src/storage/messages/control/delete_store.rs
- sdk/src/storage/messages/control/list_stores.rs
- sdk/src/storage/messages/control/mod.rs
- sdk/src/storage/messages/data/delete.rs
- sdk/src/storage/messages/data/get.rs
- sdk/src/storage/messages/data/mod.rs
- sdk/src/storage/messages/data/put.rs
- sdk/src/storage/messages/mod.rs
- sdk/src/storage/messages/momento_storage_request.rs
- sdk/src/storage/messages/storage_value.rs
- sdk/src/storage/mod.rs
- sdk/src/storage/preview_storage_client.rs
Rename StoreValue to StorageValue.
Export StorageValue so it can be matched on.
Bring the storage client exports in line with the cache client exports.
Match on item_not_found instead of element_not_found.
Add doc strings for the now public modules and files.
> fix: export StorageValue and align the exports with the cache client.

- sdk/tests/storage/control.rs
I think this test behavior might have changed when the error metadata on the server changed.
> chore: fix failing test for StoreNotFound

- sdk/src/cache/cache_client_builder.rs
- sdk/src/storage/preview_storage_client_builder.rs
- sdk/src/topics/topic_client_builder.rs
- sdk/src/utils.rs
Adjust agent header value to be colon delimited and to supply the
service name. Verified the header is sent only once.
As far as the `runtime-version` header goes, this does not make as
much sense for rust. Rust is a compiled language and does not have
an associated runtime (as in `golang`). If we do we want to include
something here, we could include the rust compiler version, though
we believe that would be uncommon.
> chore: adjust agent header value per spec

- Makefile
- example/rust/Cargo.lock
- example/rust/Cargo.toml
- example/rust/src/bin/storage.rs
- sdk/Cargo.lock
- sdk/tests/cache/control.rs
I may have to leave the bug bash a little early so started early with the Rust SDK. This might have been in your backlog/WIP already but since I was about to follow examples pattern anyway, just decided to PR it.
Note that I did NOT update the CI workflows to run this due to alpha instability.
```
my_momento_store was created
Key foo was successfully persisted in my_momento_store
Key foo found in my_momento_store with value String("bar")
Key foo was successfully deleted from my_momento_store
Store was deleted
```
> feat: add example for preview storage client

- sdk/Cargo.lock
- sdk/src/grpc/header_interceptor.rs
Because rust does not have a runtime, we send a sentinel value `rust`
for the header so that the server metrics at least have a stub value.
Also simplifies header creation and insertion with utility functions. This 
reduces code duplication.
> chore: send sentinel value for `runtime-version` header

- example/rust/README.ja.md
- example/rust/README.template.md
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1056
Fixes broken links in the `example/rust` README. 
Also updates the Japanese `example/rust` README to use `MOMENTO_API_KEY` instead of `AUTH_TOKEN` and fixes a broken link there too.
> chore: fix broken links in readmes

- sdk/src/errors.rs
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1040
When a RESOURCE_EXHAUSTED error is received, we now parse the err metadata in order to report the cause in the message wrapper. If the metadata is not available, we try to use string matching on the error details.
> chore: improve resource exhausted message

- .vscode/extensions.json
Replaces deprecated crates extension and applies recommended dependi
extension.
> chore: remove deprecated crates extension

- sdk/Cargo.lock
My local build automatically updates this in the lock file. I suspect
this wasn't committed previously. We will have to monitor after the
next release.
> chore: sdk/Cargo.lock should use correct version of momento packages

- Makefile
- sdk/Cargo.lock
In order to unblock the release, we adjust cargo publish to allow
publish on a dirty git tree.
We are actively root causing why the `Cargo.lock` file has not been
committed.
> ci: allow dirty git tree on publish

- .vscode/client-sdk-rust.code-workspace
We pulled up the sdk code from the `sdk` folder into the top-level and should update the paths in the VSCode workspaces settings accordingly.
> chore: update vscode workspace to match directory structure

- .github/workflows/on-pull-request.yml
- src/auth/auth_client.rs
- src/auth/auth_client_builder.rs
- src/auth/expiration.rs
- src/auth/messages/generate_disposable_token.rs
- src/auth/messages/mod.rs
- src/auth/messages/momento_request.rs
- src/auth/messages/permissions_conversions.rs
- src/auth/mod.rs
- src/auth/permissions/disposable_token_scope.rs
- src/auth/permissions/disposable_token_scopes.rs
- src/auth/permissions/mod.rs
- src/auth/permissions/permission_scope.rs
- src/auth/permissions/permission_scopes.rs
- src/lib.rs
- src/utils.rs
- test-util/src/cache_test_state.rs
- test-util/src/lib.rs
- test-util/src/test_utils.rs
- tests/auth/disposable_tokens.rs
- tests/auth/mod.rs
- tests/mod.rs
Work towards https://github.com/momentohq/client-sdk-rust/issues/419
- Implemented AuthClient and builder. No config object since there's no logging object to configure in this SDK like in the JS or Go ones.
- Implemented permissions structure (`PermissionScope` and `DisposableTokenScope` and related objects)
- Implemented `generate_disposable_token` method
- Added docs and doctests for public-facing objects
- Added integration tests to verify correctness of `generate_disposable_token` implementation
- Updated test-util and on-pull-request workflow to accommodate new tests
After cutting a release, I can fast-follow with updating the docs snippets example file and unit tests for the permissions conversions.
> feat: add auth client and generate_disposable_token api

- example/rust/Cargo.lock
- example/rust/Cargo.toml
- example/rust/src/docs_examples/docs_examples.rs
Follow up for https://github.com/momentohq/client-sdk-rust/issues/419
Adds code snippets for dev docs for creating an auth client and using `generate_disposable_token`
> chore: add auth client docs snippets

- example/rust/Cargo.lock
- example/rust/Cargo.toml
- example/rust/README.template.md
- example/rust/src/bin/topics.rs
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/951
Now that generate_disposable_token is implemented, I updated this example to include that as well.
> chore: showcase publisher_id in topics example

- src/auth/auth_client.rs
- src/auth/messages/generate_disposable_token.rs
- src/auth/messages/permissions_conversions.rs
- src/auth/permissions/disposable_token_scope.rs
- src/auth/permissions/disposable_token_scopes.rs
- src/auth/permissions/permission_scope.rs
- tests/auth/disposable_tokens.rs
Follow up for https://github.com/momentohq/client-sdk-rust/issues/419
Adds more unit tests for the permissions structure for the auth client to match the test coverage we have in the JS sdk.
In the process of writing these tests, I also:
- Wrote more `From` implementations to make conversion between relevant objects easier and refactored the disposable tokens integration tests to make use of these.
- Added `#[derive(Debug, Display, Clone, PartialEq)]` statements to permissions objects to make more `assert`s possible.
- Made CacheItemKey and CacheItemKeyPrefix store `Vec<u8>` directly instead of `<impl IntoBytes>` so that we can avoid the propagation of the generic type everywhere
> fix: add permission scope unit tests and From conversions for convenience

- example/rust/src/bin/topics.rs
Follow-up to https://github.com/momentohq/client-sdk-rust/pull/418
Simplifies the tokio synchronization so we can use oneshot instead.
Attempted to set up a timeout to abort the subscription task just in case, but cannot call `subscriber_handle2.abort();` from both an async timeout block and the `receiver.await` block, so opted to exclude the time bound for this example.
> chore: update topics example to use oneshot synchronization instead

- .github/workflows/on-pull-request.yml
Closes https://github.com/momentohq/client-sdk-rust/issues/429
Currently, PRs from forks cannot successfully run integration tests because they lack access to our api key secret.
This blocks open-source contributors from being able to easily work on our repo (see #422).
This PR implements the same github actions workflow we had implemented in the JS repo to allow maintainers to approve/rerun workflows on PRs from forks and allow them access to the api key secret (see https://github.com/momentohq/client-sdk-javascript/pull/1485).
> ci: allow maintainers to approve test workflow on PRs from forks

- .github/workflows/on-pull-request.yml
`checkout` was checking out the main branch rather than the merge commit (the commit that would result from merging a PR branch into main)
Caused https://github.com/momentohq/client-sdk-rust/pull/433 to appear to have no issues, so I merged it, but all following PRs failed a lint/build error (see https://github.com/momentohq/client-sdk-rust/pull/434 for that fix)
> ci: ensure we checkout the correct commit when running pr checks

- .github/workflows/on-pull-request.yml
It appears that sometimes the `merge_commit_sha` we want to check out in combination with using `on: pull_request_target` does not always exist.
This PR ensures we checkout `merge_commit_sha || pull_request.head.sha` so that it has a fallback ref that will always exist. (The head.sha is the last commit on the PR, the merge_commit_sha is the test merge with main).
Note: The updated workflow will not run on this PR because `pull_request_target` runs in the context of the base branch (main), not the PR branch.
> ci: checkout default ref on PRs if merge commit is unavailable

- .github/workflows/on-pull-request.yml
We disabled checks against the merge commit while removing the storage
client in order for CI to pass. Since we hvae removed and released the
SDK with the storage client removed, we can restore these checks.
> ci: restore checks against the merge commit

- src/cache/cache_client_builder.rs
- src/cache/config/configuration.rs
- src/config/grpc_configuration.rs
- src/config/transport_strategy.rs
- src/credential_provider.rs
Adds basic traits (eq, partialeq, clone, etc) for the cache client
builder and dependent types.
> chore: add basic trait derivations for cache client builder

- .github/workflows/on-pull-request.yml
- src/cache/cache_client_builder.rs
- src/cache/mod.rs
- src/lib.rs
In order to develop the proxy, we export the cache client builder
struct.
> chore: export cache client builder

- src/cache/mod.rs
- src/lib.rs
In order to consume a ready `CacheClientBuilder` we also have to
export this type.
> chore: export readytobuild

- .github/workflows/on-pull-request.yml
Noticed on a recent PR that the second to last commit on the PR was being used for CI instead of the most recent commit. This PR will make it so the most recent commit on a PR is checked out. 
We should also make sure that the repo has enabled "Require branches to be up to date before merging".
FYI: we ran into this issue in the JS sdk as well and updated the workflow file in the same way ([reference](https://github.com/momentohq/client-sdk-javascript/pull/1506)).
> ci: make sure on-pull-request uses latest commit

- src/errors.rs
- src/topics/config/configuration.rs
- src/topics/messages/publish.rs
- src/topics/messages/subscribe.rs
- src/topics/mod.rs
- src/topics/topic_client.rs
- src/topics/topic_client_builder.rs
- src/topics/topic_subscription_manager.rs
- tests/topics/pubsub.rs
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1158
- Added a test to confirm topic client channel can become full and silently queue up requests
- Created separate pools of grpc channels in the topic client for publish and subscribe requests
- Bookkeeping for number of active subscriptions allows the topic client to return a limit exceeded error instead of silently queueing up requests
> fix: separate publish and subscribe channels in topic client

- src/cache/cache_client.rs
- src/cache/messages/data/sorted_set/mod.rs
- src/cache/messages/data/sorted_set/sorted_set_common.rs
- src/cache/messages/data/sorted_set/sorted_set_fetch_by_rank.rs
- src/cache/messages/data/sorted_set/sorted_set_fetch_by_score.rs
- src/cache/messages/data/sorted_set/sorted_set_length_by_score.rs
- src/cache/mod.rs
- tests/cache/sorted_set.rs
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1230
Exposing support for exclusive min/max scores for `sorted_set_fetch_by_score` and `sorted_set_length_by_score`, which is needed for momento proxy.
Introduces a `ScoreBound` enum to specify inclusive or exclusive bounds.
> feat: add options for exclusive min/max for sorted set fetch by score and length by score

- src/functions/function.rs
- src/functions/messages/list_function_versions.rs
- src/functions/messages/list_functions.rs
- src/functions/messages/list_wasms.rs
- src/functions/messages/mod.rs
- src/functions/messages/put_wasm.rs
- src/functions/mod.rs
boilerplate to add these rpcs:
list_function_versions
list_functions
list_wasms
put_wasm
Since the list* rpcs are streaming, I wrote stream response types
for each, to keep things static and clean-looking.
> chore: add functions rpcs

- Cargo.lock
- Cargo.toml
- src/credential_provider.rs
- src/lib.rs
- src/protosocket/cache/cache_client.rs
- src/protosocket/cache/cache_client_builder.rs
- src/protosocket/cache/config/configuration.rs
- src/protosocket/cache/config/configurations.rs
- src/protosocket/cache/messages/scalar/get.rs
- src/protosocket/cache/messages/scalar/set.rs
- src/protosocket/cache/mod.rs
- src/protosocket/cache/utils.rs
- test-util/src/test_utils.rs
Closes https://github.com/momentohq/mr2rs/issues/2428
Uses protosocket-rpc v0.11.0 which includes TLS, TCP keepalive and so_reuseaddr settings, and connection pool management.
Updates protosocket client in sdk accordingly and exposes connection_count as a config option.
> feat: protosocket with tls and connection pool
