src/simple_cache_client.rs
tests/integration_test.rs

Closes #49
This pull request adds new delete functionality to the rust sdk.

feat(#49): Adds New Delete Function to SDK

---

src/response/cache_dictionary_fetch_response.rs
src/response/mod.rs
src/simple_cache_client.rs

Adds support for the dictionary fetch command to the Rust SDK.

feat: add dictionary fetch support to the Rust SDK

---

src/simple_cache_client.rs

Adds SDK support for the dictionary delete command.

feat: add support for dictionary delete

---

src/simple_cache_client.rs

feat: Add support for set union command to SDK

---

example/Cargo.toml
example/src/main.rs

chore: Update example crate to use momento v0.15.0

---

example/src/main.rs

chore: fix clippy warnings in example crate

---

src/simple_cache_client.rs

As in title. This was missed in #115

chore: implement list_length SDK command

---

.github/workflows/on-push-to-main.yml
Cargo.toml

This is (at the very least) a first attempt at setting up release please in this sdk

chore: set up release please

---

.github/workflows/on-push-to-main.yml

Guess the `--token` thing didn't work, adding the crate.io login step back in

chore: try logging into crates.io before publishing

---

src/cache_client.rs
src/requests/cache/list_caches.rs
src/requests/cache/mod.rs
tests/cache_control.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/177

feat: add ListCaches and initial control client integration tests

---

.github/workflows/on-pull-request.yml
Makefile

Fixes a typo in GitHub actions spec and removes unnecessary command from Makefile.

chore: fix minor issues in makefile and github actions

---

src/cache_client.rs
src/requests/cache/flush_cache.rs
src/requests/cache/mod.rs
tests/cache_control.rs

adds FlushCache and a couple integration tests

feat: add FlushCache and tests

---

src/cache_client.rs
src/requests/cache/basic/set.rs
src/requests/cache/set/set_add_elements.rs
src/requests/cache/sorted_set/sorted_set_fetch_by_rank.rs
src/requests/cache/sorted_set/sorted_set_fetch_by_score.rs
src/requests/cache/sorted_set/sorted_set_put_element.rs
src/requests/cache/sorted_set/sorted_set_put_elements.rs
tests/cache_sorted_set.rs

@malandis and @anitarua and I had another huddle about this on Friday and we decided to go back to "no with_ prefixes".

chore: remove `with_` prefixes from request builders

---

src/cache_client.rs
src/requests/cache/basic/get.rs
src/requests/cache/mod.rs
src/requests/cache/scalar/key_exists.rs
src/requests/cache/scalar/keys_exist.rs
src/requests/cache/scalar/mod.rs
src/requests/errors.rs
tests/cache_scalar.rs

Addresses part of https://github.com/momentohq/client-sdk-rust/issues/164

feat: add keyExists and keysExist

---

src/cache/mod.rs
src/cache/requests/scalar/decrease_ttl.rs
src/cache/requests/scalar/increase_ttl.rs
src/cache/requests/scalar/item_get_ttl.rs
src/cache/requests/scalar/mod.rs
src/cache/requests/scalar/update_ttl.rs
src/cache_client.rs
tests/cache_ttl.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/164

feat: add ItemGet/Update/Increase/Decrease TTL APIs

---

src/cache/mod.rs
src/cache/requests/scalar/mod.rs
src/cache/requests/scalar/set_if_absent.rs
src/cache/requests/scalar/set_if_absent_or_equal.rs
src/cache/requests/scalar/set_if_equal.rs
src/cache/requests/scalar/set_if_not_equal.rs
src/cache/requests/scalar/set_if_present.rs
src/cache/requests/scalar/set_if_present_and_not_equal.rs
src/cache_client.rs
tests/cache/scalar.rs

Last part of #164 
Adds the SetIf* methods (except for the deprecated SetIfNotExists):
- SetIfAbsent
- SetIfPresent
- SetIfEqual
- SetIfNotEqual
- SetIfPresentAndNotEqual
- SetIfAbsentOrEqual

feat: add SetIf* methods

---

src/cache/mod.rs
src/cache/requests/dictionary/dictionary_set_field.rs
src/cache/requests/dictionary/dictionary_set_fields.rs
src/cache/requests/dictionary/mod.rs
src/cache/requests/sorted_set/sorted_set_put_elements.rs
src/cache_client.rs
tests/cache/dictionary.rs

Adds `dictionary_set_fields` function, types, integration tests, and
documentation.

feat: add dictionary_set_fields

---

src/cache/mod.rs
src/cache/requests/dictionary/dictionary_fetch.rs
src/cache/requests/list/list_fetch.rs
src/cache/requests/list/list_length.rs
src/cache/requests/list/list_pop_back.rs
src/cache/requests/list/list_pop_front.rs
src/cache/requests/scalar/get.rs
src/cache/requests/scalar/item_get_ttl.rs
src/cache/requests/scalar/item_get_type.rs
src/cache/requests/sorted_set/mod.rs
src/cache/requests/sorted_set/sorted_set_fetch_response.rs
src/cache/requests/sorted_set/sorted_set_get_rank.rs
src/cache/requests/sorted_set/sorted_set_get_score.rs
src/cache/requests/sorted_set/sorted_set_length.rs
src/cache/requests/sorted_set/sorted_set_remove_elements.rs
src/cache_client.rs
src/errors.rs
tests/cache/sorted_set.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/168

feat: add more sorted set methods

---

src/cache/mod.rs
src/cache/requests/dictionary/dictionary_remove_fields.rs
src/cache/requests/dictionary/mod.rs
src/cache_client.rs
tests/cache/dictionary.rs

Adds the `dictionary_remove_fields` command, request and response types, integration tests, and documentation.

feat: implement dictionary remove fields

---

src/cache/mod.rs
src/cache/requests/set/mod.rs
src/cache/requests/set/set_add_elements.rs
src/cache/requests/set/set_fetch.rs
src/cache/requests/set/set_remove_elements.rs
src/cache_client.rs
tests/cache/mod.rs
tests/cache/set.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/167

feat: add set_fetch and set_remove_elements

---

src/cache/mod.rs
src/cache/requests/dictionary/dictionary_get_field.rs
src/cache/requests/dictionary/dictionary_get_fields.rs
src/cache_client.rs
tests/cache/dictionary.rs

Add `dictionary_get_field` command, request and response types,
integration tests, and documentation.

feat: implement dictionary get field

---

example/Cargo.toml
example/README.md
example/src/bin/docs_examples.rs
src/cache_client.rs
src/topics/topic_client.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/210

chore: add snippets for dev docs, corrected some docstring examples in cache client

---

src/cache/cache_client.rs
src/cache/messages/scalar/decrease_ttl.rs
src/cache/messages/scalar/increase_ttl.rs
src/cache/messages/scalar/increment.rs
src/cache/messages/scalar/item_get_ttl.rs
src/cache/messages/scalar/item_get_type.rs
src/cache/messages/scalar/keys_exist.rs
src/cache/messages/scalar/update_ttl.rs
src/cache/messages/sorted_set/sorted_set_put_element.rs
src/cache/messages/sorted_set/sorted_set_put_elements.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/258

chore: audit docs for usage of key/field/value

---

src/errors.rs
src/topics/messages/publish.rs
src/topics/messages/subscribe.rs
src/topics/messages/subscription.rs
src/topics/topic_client.rs
test-util/src/cache_test_state.rs
test-util/src/lib.rs
test-util/src/test_data.rs
test-util/src/test_utils.rs
tests/mod.rs
tests/topics/mod.rs
tests/topics/pubsub.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/277

chore: add integration tests and doctests for TopicClient

---

src/cache/cache_client.rs

Addresses part of https://github.com/momentohq/client-sdk-rust/issues/284

chore: add missing links in docs, small docs fixes

---

src/cache/cache_client.rs
src/cache/messages/list/list_concatenate_back.rs
src/cache/messages/list/list_concatenate_front.rs
src/cache/messages/list/list_push_back.rs
src/cache/messages/list/list_push_front.rs
src/cache/messages/list/mod.rs
src/cache/mod.rs
tests/cache/list.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/278
Also fixes a couple of the list-related tasks in https://github.com/momentohq/client-sdk-rust/issues/284

feat: add list_push_front and list_push_back

---

build.rs
src/errors.rs
src/utils.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/297

chore: add more docstrings for errors and utils, remove unused file

---

src/cache/cache_client.rs
src/cache/config/configuration.rs
src/config/grpc_configuration.rs
src/config/transport_strategy.rs
src/credential_provider.rs
src/lib.rs
src/topics/config/configuration.rs
src/topics/topic_client.rs

Addresses https://github.com/momentohq/client-sdk-rust/issues/283

chore: add docs to improve discoverability for client instantiation

---

sdk/Cargo.lock
sdk/src/cache/cache_client.rs
sdk/src/cache/messages/data/sorted_set/mod.rs
sdk/src/cache/messages/data/sorted_set/sorted_set_get_score.rs
sdk/src/cache/messages/data/sorted_set/sorted_set_get_scores.rs
sdk/src/cache/messages/data/sorted_set/sorted_set_increment_score.rs
sdk/src/cache/messages/data/sorted_set/sorted_set_put_elements.rs
sdk/src/cache/mod.rs
sdk/tests/cache/sorted_set.rs

closes https://github.com/momentohq/client-sdk-rust/issues/359

feat: add sorted_set_get_scores and sorted_set_increment methods

---

sdk/src/grpc/header_interceptor.rs

Previously we used a `static` variable to keep track of whether the
agent header was sent. This would send one agent header
unconditionally of the client type.
In order to send a single agent header per client type (cache vs
topics vs store) we make the variable an instance variable of the
`HeaderInterceptor`.

fix: interceptor should send only once per client

---

sdk/src/topics/messages/subscription.rs

Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/934

fix: publisher_id was missing from received subscription items

---

example/rust/Cargo.lock
example/rust/Cargo.toml
example/rust/src/bin/storage.rs

An addition to https://github.com/momentohq/dev-eco-issue-tracker/issues/936
Updated the storage get responses but also needed to update them in the storage example

chore: update examples momento dep and update storage example get responses

---

example/rust/src/docs_examples/cheat_sheet_storage_client.rs
example/rust/src/docs_examples/docs_examples.rs
sdk/Cargo.lock

Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/943
Cargo also auto-generated an updated sdk/Cargo.lock file so that's included here as well.

chore: add dev docs snippets and cheat sheet for storage client

---

LICENSE
sdk/Cargo.lock
sdk/Cargo.toml
sdk/src/topics/messages/subscribe.rs
sdk/src/topics/messages/subscription.rs
sdk/src/topics/topic_client.rs

- Update protos version
- Add sequence page to topics
- Fix copyright name in LICENSE file
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1064

feat: add sequence page to topics

---

sdk/src/cache/cache_client.rs
sdk/src/cache/messages/data/scalar/get.rs
sdk/src/cache/messages/data/scalar/get_batch.rs
sdk/src/cache/messages/data/scalar/mod.rs
sdk/src/cache/messages/data/scalar/set.rs
sdk/src/cache/messages/data/scalar/set_batch.rs
sdk/src/cache/mod.rs
sdk/tests/cache/batch.rs
sdk/tests/cache/mod.rs

Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/952

feat: add get_batch and set_batch

---

sdk/Cargo.lock

Updates cargo lock from last release.

chore: update cargo lock

---

src/auth/expiration.rs
tests/auth/disposable_tokens.rs

Follow up for https://github.com/momentohq/client-sdk-rust/issues/419
Just adding more test cases for completeness for the recent auth additions

chore: add unit tests for expiration objects and expand all_data_read_write disposable token test for completeness

---

example/rust/src/bin/topics.rs

This PR will fix the lint/build error caused by https://github.com/momentohq/client-sdk-rust/pull/433
That error was not caught due to a bug in the CI workflow (it checks out main branch instead of the merge commit, aka the that would result from merging the PR branch into main).

chore: update topics example to use updated auth client UX

---

.github/workflows/on-pull-request.yml

We temporarily disabled in order fo ra PR to pass.

ci: restore checks against head ref
